### ISSUE TITLE
Release build is not showing anvil contracts ABI

### ISSUE THREAD

**Issue by DavideSilva** [ethui/ethui#553]
The contract ABI (and name) is not appearing in the release build of Iron when deploying contracts locally using Anvil

On the left is the release build, on the right the dev build

<img width="1815" alt="image" src="https://github.com/iron-wallet/iron/assets/2940022/f8aa7e47-9dc7-46f1-bb97-39724db0868c">

**Comment by naps62** [comment]
@DavideSilva I believe this is also solved now, right?

**Comment by DavideSilva** [comment]
Correct, this is solved
