### ISSUE TITLE
Add dev network toggle

### ISSUE THREAD

**Issue by mike-code** [ethui/ethui#565]
This will be very low prio but I'd like to leave it here

We're running some dev networks which have chain id 1337 instead of 31337 (can't really tell why). Thus it'd be useful to have dev network toggle instead of hardcoded `self.chain_id == 31337`

**Comment by naps62** [comment]
This is reasonable, and something I've thought about as well (but haven't needed yet)

I'm not sure what the best way to go about it, thought.
As an initial approach, perhaps `self.chain_id = 31337 || self.chain_id = 1337` could work? or did you have something else in mind?

**Comment by naps62** [comment]
already added `force_is_anvil` recently to solve this. forgot to link to this issue at the time
