### ISSUE TITLE
Invalid argument when passing a `bytes32[]` value to a Contract

### ISSUE THREAD

**Issue by DavideSilva** [ethui/ethui#623]
Passing a `bytes32[]` value as an argument in the Contracts tab does nothing, with an `InvalidArrayError` message appearing on the dev console

<img width="1304" alt="image" src="https://github.com/ethui/ethui/assets/2940022/2c846110-1044-4aa9-80d4-41b10943995c">

**Comment by naps62** [comment]
Fixed in #628
