### ISSUE TITLE
Contract tab not updating after a new contract deploy

### ISSUE THREAD

**Issue by DavideSilva** [ethui/ethui#624]
Deploying a contract using another contract from the Contracts tab, requires a reopen of the app in order to correctly display the new contract's name and functions

After deploying and before closing
![image](https://github.com/ethui/ethui/assets/2940022/8c2eff19-be32-4406-8967-f071900dc109)

After reopening the app, without touching anvil
![image](https://github.com/ethui/ethui/assets/2940022/7acf0a8f-518c-4600-b372-a055a08e7368)

**Comment by naps62** [comment]
fixed in #626
