### ISSUE TITLE
Read functions are not triggering a call to anvil

### ISSUE THREAD

**Issue by DavideSilva** [ethui/ethui#631]
In the latest version, 1.5.2, the `read` functions of a contract are not interacting with the local anvil node, while the `write` functions seem to work as intended. This seems to not be occurring when running the app in dev mode, as seen in the screenshot below

![image](https://github.com/ethui/ethui/assets/2940022/c5f31ebd-1662-4c3f-b024-bd77eb4196d3)

**Comment by naps62** [comment]
Fixed in the latest release
