### ISSUE TITLE
x86_64 version for old macs?

### ISSUE THREAD

**Issue by 0xaaiden** [ethui/ethui#675]
Are there plans to release binaries for x86_64 macs? 
I own an old mac and I'm trying to run ethui for a local project and not able to build locally

**Comment by naps62** [comment]
Hey there @0xaaiden 

I didn't realize we were only building for aarch64 until you asked, so I guess this was an oversight when I first worked on the build process. Also, all of my apple-using coworkers use more recent ones I believe, so this never came up in the early tests

I will note a couple of things:
- tauri's docs state `The minimum version of the operating system required for a Tauri app to run on macOS is 10.13` ([source](https://tauri.app/v1/guides/building/macos/))
- our frontend build is targeting `safari14`

I honestly don't know enough about the apple ecosystem to know if these could be an issue to you as well.

As for the compilation target, hopefully it's as should be as simple as adding a new release job with this target to the CI. I can work on that tomorrow

thanks for reporting!

**Comment by naps62** [comment]
@0xaaiden at the end of this build you will find an artifact, which you can download, extract, and hopefully install & run
https://github.com/ethui/ethui/actions/runs/9258517515

can you let me know whether or not it works? unfortunately I don't think I have a good way to test it myself (I have a local VM, but only for the aarch64 target, and it was quite a pain to set up a few months ago)
