### ISSUE TITLE
Token balance should take into consideration the number of decimal places

### ISSUE THREAD

**Issue by DavideSilva** [ethui/ethui#676]
Using an ERC20 mock contract that only uses 6 decimals, the token balance appears as < 0.001 when the actual balance is 1000. If we can, we should format the token balance according to the number of decimals used

<img width="1101" alt="image" src="https://github.com/ethui/ethui/assets/2940022/88f87500-0f80-4663-9fd4-0612fe4e19ae">

<img width="1101" alt="image" src="https://github.com/ethui/ethui/assets/2940022/6de838f7-3bbe-41ad-be66-e03331a91885">

<img width="1101" alt="image" src="https://github.com/ethui/ethui/assets/2940022/d8a9b10a-6746-4ae2-b86d-45b1bbbb7e0f">

**Comment by od-hunter** [comment]
Is this open for contribution, if yes can I be assigned please?

**Comment by Abhii5496** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/ethui-formerly-iron-wallet).

### My background and how it can be leveraged
I'm a frontend dev with 2 years of experience . Recently i have been learning web3 dev and i learned quite few things. I can give it a try

### How I plan on tackling this issue
function formatBalance(balance, decimals) {
    return (balance / Math.pow(10, decimals)).toFixed(decimals);
} we can pass the balance and decimals and it will be calculated
