### ISSUE TITLE
Wallet icons

### ISSUE THREAD

**Issue by naps62** [ethui/ethui#778]
we already have network icons, and an accompanying `<ChainView />` component
we now want to have icons for each of the different wallet types. perhaps lucide-react already has some icons useful for some, but this likely involves spelunking the web for appropriate SVGs

**Comment by caxtonacollins** [comment]
i will love to be assigned this issue. please assign me

**Comment by naps62** [comment]
@caxtonacollins yes, but you asked that on two separate issues, so I'd kindly ask you to stick with just one for now

**Comment by mimisavage** [comment]
May I take care of this?
