### ISSUE TITLE
Wallet unlock dialog is not following dark mode preference

### ISSUE THREAD

**Issue by DavideSilva** [ethui/ethui#822]
When unlocking a password protected wallet, the dialog has a white background, when on dark mode

Also, there are some spacing padding issues with the buttons and the `unlocking...` text
Unlock button should have a spinner to indicate loading state

![image](https://github.com/user-attachments/assets/4fce6390-1613-46af-b85e-4975c62fa5a2)
![image](https://github.com/user-attachments/assets/ad9bdb75-dea8-4b66-a096-caaf9094da3c)

**Comment by naps62** [comment]
Will open a separate issue for the UI details you mentioned
