### ISSUE TITLE
Hiding an already hidden window crashes the app

### ISSUE THREAD

**Issue by DavideSilva** [ethui/ethui#852]
The app crashes by clicking the hide menu option in the system tray while the app is already minimised

```thread 'main' panicked at bin/src/system_tray.rs:31:50:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /Users/davidesilva/Developer/ethui-dev/crates/forge/src/watcher.rs:100:25:
called `Result::unwrap()` on an `Err` value: SendError { .. }
```

**Comment by DavideSilva** [comment]
Sorry, pasted the wrong error message, it should be this one

```
thread 'main' panicked at bin/src/system_tray.rs:31:50:
called `Option::unwrap()` on a `None` value
```

**Comment by naps62** [comment]
ok I tried reproducing it first, and it wasn't happening.
now I see the issue. if you hide the window from the system tray, and then do it a second time, it doesn't crash (I guess the window is just "hidden" and not "destroyed"?)

if you actually close the window (Super+Q on my Linux), and then try to hide it, it crashes

how do you reproduce this on macos? I'm running into a different problem, where "Close Window (Cmd+W) doesn't do anything

**Comment by DavideSilva** [comment]
> how do you reproduce this on macos?

ethui needs to start already minimised by enabling that in the Settings. With that enabled, I simply click the hide option in the system tray icon to cause the crash

**Comment by naps62** [comment]
> yes, I can reproduce it too

then this part is likely another mac-specific event we need to track
